apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: users-secrets
  namespace: users
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: users-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: production/rds/postgres-v4
        property: DB_HOST
    - secretKey: DB_USERNAME
      remoteRef:
        key: production/rds/postgres-v4
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: production/rds/postgres-v4
        property: DB_PASSWORD
    - secretKey: DB_USERS_NAME
      remoteRef:
        key: production/rds/postgres-v4
        property: DB_USERS_NAME
    - secretKey: DB_ENGINE
      remoteRef:
        key: production/rds/postgres-v4
        property: DB_ENGINE
    - secretKey: DB_PORT
      remoteRef:
        key: production/rds/postgres-v4
        property: DB_PORT
