apiVersion: v1
kind: Service
metadata:
  name: api-food-service
  namespace: users
spec:
  type: ClusterIP
  selector:
    app: api-food-users
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
