spring:
  config:
    import: aws-secretsmanager:production/rds/postgres-v3
  cloud:
    aws:
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY:kaka}
        secret-key: ${AWS_SECRET_KEY:kiki}
  profiles:
    active: ${ENVIRONMENT_PROFILE_VALUE:prd}
  application:
    name: api-food
  datasource:
    url: jdbc:postgresql://${db_host}:5432/food_db
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver
server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.springframework: ${SPRING_LOG_LEVEL:INFO}
    br.com.five.seven.food: ${APP_LOG_LEVEL:DEBUG}
security:
  jwt:
    secret: ${JWT_SECRET:default-jwt-secret-key-for-dev-only}
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

user: ${ADMIN_USER:admin}
pass: ${ADMIN_PASS:admin}

