spring:
  config:
    import: aws-secretsmanager:production/rds/postgres-v3
  cloud:
    aws:
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
  datasource:
    url: jdbc:postgresql://${db_host}:5432/food_oders_db
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
