spring:
  profiles:
    active: ${ENVIRONMENT_PROFILE_VALUE:prd}
  application:
    name: api-food
  datasource:
    url: jdbc:postgresql://localhost:5432/fooddb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.springframework: ${SPRING_LOG_LEVEL:INFO}
    br.com.five.seven.food: ${APP_LOG_LEVEL:DEBUG}
security:
  jwt:
    secret: ${JWT_SECRET:default-jwt-secret-key-for-dev-only}
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

user: ${ADMIN_USER:admin}
pass: ${ADMIN_PASS:admin}
