name: CI

on:
  push:
    branches: [ develop, main ]
    paths-ignore:
      - 'k8s/**'
  workflow_dispatch: {}

jobs:
  call-reusable-build-and-test-workflow:
    uses: railsonribeiro/nested-reusable-java-maven-eks-fork/.github/workflows/build.yml@main
    with:
      app_name: "pos-tech-g57-app-users"
    secrets: inherit
